version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - static-vol:/app/backend/staticfiles/
    stdin_open: true
    tty: true
    #command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 51010:8000
    #expose:
    #  - 8000
volumes:
  static-vol: 